[package]
name = "rustsynth-sys"
description = "Low level bindings to VapourSynth"
version = "0.3.0"
edition = "2021"
license = "LGPL-2.1"
authors = ["Anima <contact@animafps.xyz>"]
repository = "https://github.com/animafps/rustsynth"

[build-dependencies]
bindgen = "0.59"
