[package]
name = "example_plugin"
version = "0.1.0"
edition = "2021"

[dependencies]
rustsynth = { path = "../rustsynth", features = ["proc-macro"]}

[features]
plugin = []

[lib]
name = "example_plugin"
crate-type = ["cdylib"]