[package]
name = "rustsynth"
version = "0.1.0"
edition = "2021"
license = "LGPL-2.1"
description = "Safe VapourSynth wrapper"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustsynth-sys = "0.1"
