[workspace]
resolver = "2"
members = ["rustsynth", "rustsynth-sys", "rustsynth-derive", "example", "rspipe"]

[workspace.package]
edition = "2021"
license = "LGPL-2.1"
authors = ["Anima <contact@animafps.xyz>"]
repository = "https://github.com/animafps/rustsynth"
