[package]
name = "rustsynth"
version = "0.2.1"
edition = "2021"
license = "LGPL-2.1"
description = "Safe VapourSynth wrapper"
authors = ["Anima <contact@animafps.xyz>"]
repository = "https://github.com/animafps/rustsynth"
categories = ["multimedia::video", "api-bindings"]
keywords = ["vapoursynth"]

[dependencies]
rustsynth-sys = {version = "0.1", path = "../rustsynth-sys"}
