name: Build and Release Docs
on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  docs:
    name: Build and Release Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Cache zimg
        uses: actions/cache@v4
        id: cache-zimg
        with:
          path: /usr/local/lib/libzimg*
          key: ${{ runner.os }}-zimg-3.0.6
      - name: Cache vapoursynth
        uses: actions/cache@v4
        id: cache-vapoursynth
        with:
          path: |
            /usr/local/lib/libvapoursynth*
            /usr/local/include/vapoursynth
          key: ${{ runner.os }}-vapoursynth-${{ hashFiles('rustsynth-sys/vapoursynth/**') }}
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get --yes install g++ make autoconf automake libtool pkg-config nasm git libclang-dev python3 python3-dev
          pip install Cython
      - name: Build zimg
        if: steps.cache-zimg.outputs.cache-hit != 'true'
        run: |
          git clone --branch release-3.0.6 --depth 1 https://github.com/sekrit-twc/zimg.git
          cd zimg
          ./autogen.sh
          ./configure
          make
          sudo make install
      - name: Build vapoursynth
        if: steps.cache-vapoursynth.outputs.cache-hit != 'true'
        run: |
          cd rustsynth-sys/vapoursynth
          ./autogen.sh
          ./configure
          make
          sudo make install
      - name: Run doc
        run: |
          cargo doc --workspace --no-deps --exclude example_plugin
      - name: Deploy documentation
        uses: actions/upload-pages-artifact@v3
        with:
          path: target/doc
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4